POST http://localhost:8080/events
Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE3Nzc2MjUxLCJ1c2VySWQiOjB9.CT63a5NNLTNC8wK1M5d4eUpuu9iNCzHOMsu7g4UsSVA
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE3Nzc3Mjg3LCJ1c2VySWQiOjJ9.EOdBxjp3c7YK5BMFq0zMOXwRpqMFO455WXudxy4zWKw

{
    "name": "Test Event",
    "description": "A test event",
    "location": "test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}