DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiZXhwIjoxNzE3Nzc3Mjg3LCJ1c2VySWQiOjJ9.EOdBxjp3c7YK5BMFq0zMOXwRpqMFO455WXudxy4zWKw
